[versions]
kotlin = "2.0.20"

[libraries]
kotest-bom = { module = "io.kotest:kotest-bom", version = "5.9.1" }
kotest-assertions-shared = { module = "io.kotest:kotest-assertions-shared" }
kotest-framework-api = { module = "io.kotest:kotest-framework-api" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5" }

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinter-gradle-plugin = { module = "org.jmailen.kotlinter:org.jmailen.kotlinter.gradle.plugin", version = "4.0.0" }

semver4j = { module = "com.github.gundy:semver4j", version = "0.16.4" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version = "2.1.4" }
kotlinter = { id = "org.jmailen.kotlinter", version = "4.3.0" }
taskTree = { id = "com.dorongold.task-tree", version = "4.0.0" }
versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }
duplicateClasses = { id = "net.idlestate.gradle-duplicate-classes-check", version = "1.2.0" }
