name: Build

on:
  push:
    branches-ignore:
      - 'abandoned-*'

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
#          driver: cloud
#          endpoint: "mahoney266/lidalia-world-gha"
          install: true

      - uses: docker/build-push-action@v5
        with:
          target: build-output
          outputs: 'type=local,dest=build'
          provenance: false

      - uses: docker/build-push-action@v5
        if: ${{ hashFiles('build/failed') != '' }}
        with:
          provenance: false

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Unit Test Results
          junit_files: |
            build/test-results/**/*.xml

      - name: Archive build results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build
          path: build

      - name: Archive output
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jars
          path: build/libs
